service: countries-info-service

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: dev

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  getCountriesInfo:
    handler: get_countries_info.lambda_handler
    events:
      - http:
          path: /countries_info
          method: GET
    timeout: 30
package:
  exclude:
    - venv/**
    - tests/**
    - test_local_lambda_handler.py
    - README.md
    - .env
    - __pycache/**